services:
  db:
    image: timescale/timescaledb:latest-pg16
    container_name: timetable_db
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=secure_password
      - POSTGRES_DB=timetable_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
        
  mqtt:
    image: eclipse-mosquitto:latest
    container_name: mqtt_broker
    ports:
      - "1883:1883"
  app:
    build: .
    container_name: timetable_app
    ports:
      - "8000:8000"
volumes:
  postgres_data: